name: Build APK for Kotlin Multiplatform App
on:
  push:
    branches:
      - master  # ajuste de acordo com o nome da sua branch principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: 8
